import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { ImageCard } from "@/components/ImageCard";


import data from "@/data/images.json";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

async function getProductImages() {
  const images = data

  if (!images) {
    return { error: "Failed to fetch images" };
  }

  return images;
}

export async function getStaticProps() {
  const images = await getProductImages();
  return {
    props: {
      images
    },
  };
}

export default function Home({ images } : any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <h1 className={styles.title}>Image Optimization</h1>
        <div className={styles.grid}>
          {images?.map((image : {src: string, title: string}, index: number) => (
            <ImageCard
              key={index}
              src={image?.src}
              alt={image?.title}
            />
          ))}
        </div> 
      </div>
    </>
  );
}
